version: 0.1

phases:
  install:
    commands:
      - echo Entering install phase...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 015404077857.dkr.ecr.eu-central-1.amazonaws.com
      - aws sts get-caller-identity
      - echo updating kubeconfig...
      # Install kubectl
      - curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.10/2019-06-21/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      - kubectl version --short --client
      # Install Iam Authenticator
      - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$HOME/bin:$PATH
      - aws-iam-authenticator help
      # Configure kubectl
      - aws eks --region eu-central-1 update-kubeconfig --name wincom-web
  build:
    commands:
      - echo Build started on `date`
      - gradle bootBuildImage
      - docker tag wincom:0.0.1-SNAPSHOT 015404077857.dkr.ecr.eu-central-1.amazonaws.com/wincom-web
  post_build:
    commands:
      - docker push 015404077857.dkr.ecr.eu-central-1.amazonaws.com/wincom-web
      - aws sts get-caller-identity
      - kubectl apply -f wincom-web-eks.yaml
      - kubectl rollout restart deployment/wincom-web
artifacts:
  type: image
