// elastic adaptive
export const SET_CURRENT_FONT_SIZE = 'SET_CURRENT_FONT_SIZE'
export const SET_USER_DEVICE_TYPE = 'SET_USER_DEVICE_TYPE'

// ui
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const TOGGLE_SIDEBAR_COLLAPSE = 'TOGGLE_SIDEBAR_COLLAPSE'

// filtration
export const RESET_FILTERS = 'RESET_FILTERS'
export const SET_OWNER_FILTER_VALUE = 'SET_OWNER_FILTER_VALUE'
export const SET_CATEGORY_FILTER_VALUE = 'SET_CATEGORY_FILTER_VALUE'
export const SET_STATUS_FILTER_VALUE = 'SET_STATUS_FILTER_VALUE'
export const SET_DRIVERS_FILTER_VALUE = 'SET_DRIVERS_FILTER_VALUE'
